language: java
env:
  global:
      - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2048m -Xms1024m"  
jdk:
  - oraclejdk7
sudo: false
script:
- cd releng/org.obeonetwork.m2doc.parent/
- mvn -v
- mvn clean verify 
deploy:
  provider: releases
  api_key: "c5b0bc1cc4aad539166e8d35a68e65f3212e283f"
  file: 
  - "releng/org.obeonetwork.m2doc.update/target/org.obeonetwork.m2doc.update-0.7.0-SNAPSHOT.zip"
  - "dependencies/org.apache.poi.update/target/org.apache.poi.update-0.7.0-SNAPSHOT.zip"
  skip_cleanup: true
  on:
    tags: true
