language: java
env:
  global:
  - DISPLAY=:99.0
  - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2048m -Xms1024m"  
jdk:
- oraclejdk7
sudo: false
install: true
before_script:
- export SWT_GTK3=0
- /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1440x900x16
- sh -e /etc/init.d/xvfb start
- sleep 10
script:
- cd releng/org.obeonetwork.m2doc.parent/
- mvn -v
- mvn clean verify 
- cd ../..
- if [[ "$TRAVIS_TAG" != "" ]]; then chmod a+x prepare-deploy-local-dir.sh && ./prepare-deploy-local-dir.sh $TRAVIS_BUILD_DIR/$TRAVIS_TAG; fi
after_script:
- if [[ "$TRAVIS_TAG" != "" ]]; then chmod a+x travis-promote.sh && ./travis-promote.sh; fi
deploy:
###### Release ######
- provider: s3
  access_key_id: AKIAJFIXOUR3SFD7OGMA
  secret_access_key:
    secure: LblUlvcnFMBPYWYhuvnZsCSpVx+qOzDR8gWIk/FRBuL87DK9DU4TXMlJVdrPNvzeU53uzbtkzmv1VgW1X7qBJ/Hd2HiB9vIQik8cMXcNI17wTTQPsgoSUawtefZT4UaznwlepL3t1fS+6vKtyUCtJOvt4gEskO95RriZfqXvbQLjm3WNqh7e68CmHNy7Zf8aBiviqlvZT0Td6fqeb9i+w18WqcbIUDaI26blEhl4hR1d9fSFERA/XEyetTEinbXTruAsA+T86SnsRFJVmTXOidb2BjrOP6EepkkR5SFyZuYQ8Y/75WvBQ30ShwA5iVuVOSGTgA6nYaYT+fiWe3K4Eo6AyE5vTg6BpAuWmE4IvoeXHeIbnXXOFkbzfv3didBGzqDPeDvAeFtyRqNEfbxB+mxQ6EdS08UkRQRXlseCNXJ6v1lO6iCpc9E1O0ZnPKDVZ7UKf1n/bvbUMi/ExUk2sTqfFhT1e9CnLCzBVcJ8lddF4HPEKnppW+JmAG0unHn/PVruSbH2L+SUk3k3DK4xH08OPV8SVvODFmB2hfy87gMyuRcTiHzSZPd/yTwd0TdLw7tIk+3fWMG0vof5/U2bhofqHzNcEHbOXG2hIQIUXrp1yn+HpWPtjnBv0D0Y9AFK6OMVbjqD4UfWZbaMTKhJ6rpAcIhuESBndgHKRNW05K8=
  bucket: obeo-m2doc-releases
  local-dir: "${TRAVIS_BUILD_DIR}/${TRAVIS_TAG}"
  acl: public_read
  skip_cleanup: true
  region: eu-west-1
  upload-dir: ${TRAVIS_TAG}
  on:
    tags: true
    all_branches: true
    repo: ObeoNetwork/M2Doc

