dist: trusty
language: java
env:
  - PROFILE=platform-oxygen,tests
  - PROFILE=platform-photon,tests
  - PROFILE=platform-2018-12,tests
  - PROFILE=platform-2019-12,tests,updatesites
  - PROFILE=platform-2020-03,tests
#  - PROFILE=platform-2020-12,tests
  - PROFILE=platform-sirius-5.1.1,tests
  - PROFILE=platform-sirius-6.0.0,tests
  - PROFILE=platform-sirius-6.1.3,tests
  - PROFILE=platform-sirius-6.2.2,tests
  - PROFILE=platform-sirius-6.2.x,tests
  - PROFILE=platform-sirius-6.3.5,tests
  - PROFILE=platform-sirius-6.3.x,tests
  - PROFILE=platform-sirius-6.4.0,tests
  - PROFILE=platform-sirius-6.4.x,tests
  - PROFILE=platform-capella-1.4.2,tests
jdk:
- oraclejdk8
- oraclejdk11

jobs:
  exclude:
    # Java 8 only
  - jdk: oraclejdk11
    env: PROFILE=platform-oxygen,tests
  - if: type = cron
    jdk: oraclejdk8
    env: PROFILE=platform-oxygen,tests

  - jdk: oraclejdk11
    env: PROFILE=platform-photon,tests
  - if: type = cron
    jdk: oraclejdk8
    env: PROFILE=platform-photon,tests

  - jdk: oraclejdk11
    env: PROFILE=platform-sirius-5.1.1,tests
  - if: type = cron
    jdk: oraclejdk8
    env: PROFILE=platform-sirius-5.1.1,tests

    # Java 11 only
  - jdk: oraclejdk8
    env: PROFILE=platform-2018-12,tests
  - if: type = cron
    jdk: oraclejdk11
    env: PROFILE=platform-2018-12,tests

  - jdk: oraclejdk8
    env: PROFILE=platform-2019-12,tests,updatesites
  - if: type = cron
    jdk: oraclejdk11
    env: PROFILE=platform-2019-12,tests,updatesites

  - jdk: oraclejdk8
    env: PROFILE=platform-2020-03,tests
  - if: type = cron
    jdk: oraclejdk11
    env: PROFILE=platform-2020-03,tests

  - jdk: oraclejdk8
    env: PROFILE=platform-2020-12,tests
  - if: type = cron
    jdk: oraclejdk11
    env: PROFILE=platform-2020-12,tests

  - jdk: oraclejdk8
    env: PROFILE=platform-sirius-6.0.0,tests
  - if: type = cron
    jdk: oraclejdk11
    env: PROFILE=platform-sirius-6.0.0,tests

  - jdk: oraclejdk8
    env: PROFILE=platform-sirius-6.1.3,tests
  - if: type = cron
    jdk: oraclejdk11
    env: PROFILE=platform-sirius-6.1.3,tests

  - jdk: oraclejdk8
    env: PROFILE=platform-sirius-6.2.2,tests
  - if: type = cron
    jdk: oraclejdk11
    env: PROFILE=platform-sirius-6.2.2,tests

  - jdk: oraclejdk8
    env: PROFILE=platform-sirius-6.2.x,tests

  - jdk: oraclejdk8
    env: PROFILE=platform-sirius-6.3.5,tests
  - if: type = cron
    jdk: oraclejdk11
    env: PROFILE=platform-sirius-6.3.5,tests

  - jdk: oraclejdk8
    env: PROFILE=platform-sirius-6.3.x,tests

  - jdk: oraclejdk8
    env: PROFILE=platform-sirius-6.4.0,tests
  - if: type = cron
    jdk: oraclejdk11
    env: PROFILE=platform-sirius-6.4.0,tests

  - jdk: oraclejdk8
    env: PROFILE=platform-sirius-6.4.x,tests

  - jdk: oraclejdk8
    env: PROFILE=platform-capella-1.4.2,tests
  - if: type = cron
    jdk: oraclejdk11
    env: PROFILE=platform-capella-1.4.2,tests

sudo: required
install: true
before_script:
# for RCPTT tests
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1440x900x16"
- sh -e /etc/init.d/xvfb start
- export DISPLAY=:99.0
- export MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2048m -Xms1024m"
# for the web site
- if [[ "$PROFILE" == *"updatesites"* ]]; then chmod a+x ./scripts/website-install.sh && ./scripts/website-install.sh; fi
# for the MS Word add-in
- if [[ "$PROFILE" == *"updatesites"* ]]; then chmod a+x ./scripts/word-add-in-install.sh && ./scripts/word-add-in-install.sh; fi
script:
# Build documentation web site
- mkdir plugins/org.obeonetwork.m2doc.doc/doc
- if [[ "$PROFILE" == *"updatesites"* ]]; then chmod a+x ./scripts/website-build.sh && ./scripts/website-build.sh; fi
# Build MS Word add-in
- mkdir plugins/org.obeonetwork.m2doc.word.addin/dist/
- if [[ "$PROFILE" == *"updatesites"* ]]; then chmod a+x ./scripts/word-add-in-build.sh && ./scripts/word-add-in-build.sh; fi
# Java build
- mvn -v
- mvn clean verify -fae -P$PROFILE
- export TAG_OR_BRANCH="${TRAVIS_BRANCH}/nightly"
- if [[ "$TRAVIS_TAG" != "" ]]; then export TAG_OR_BRANCH="${TRAVIS_TAG}"; fi
- if [[ "$PROFILE" == *"updatesites"* ]]; then chmod a+x ./scripts/prepare-deploy-local-dir.sh && ./scripts/prepare-deploy-local-dir.sh
  $TRAVIS_BUILD_DIR/$TAG_OR_BRANCH; export UPDATE_SITES=true; fi
after_script:
- if [[ "$TAG_OR_BRANCH" != "" ]]; then chmod a+x ./scripts/travis-promote.sh && ./scripts/travis-promote.sh;
  fi
deploy:
- provider: s3
  access_key_id: AKIAI7GYGSUKTIBLAI6Q
  secret_access_key:
    secure: A2AARWNQrm5bddsfzArzH8miOVvoTjT/Y1P6CMUHqiwKRE46mYEPqVxy+CIPtVa8SmvFTL/IRxb8zQ8FPBSTasB0vzz94yxtVJvwn+kkPM+z0YdzOfonJo4BjKO+NHzgncOpvBngMqboU5RzS+pqQ6xUhALhHEATCARsYF0NUgsEjGZ8JJJSzAbfQ7oaL6xbuon/72ABJOIQbg9sesq7YFl+/9bHcOl1SU5owF9hIa/b6IB3iEmg1L2vzYP2L/x+BGPwpMkDfRGMUBJByf3e8q6mvPYU/5XVQrqo2WnD9JGQB62OOi/DlRQ0cHxXP9x5iRd1hVqMJZMduAAa5ymK8UOV5h1+xkBFJMQZ3UQbZ3FEG/0rYFEVZ/ynj8H05/nO1DxqTiGSaCIlbF8hEWvcqfoK/cT+v+9i4GJ3jael03Um90U7L2fI098VYJmAuWqcYyNTqDVb5hwD77ULvT2b13vtVAGEJO1h3UoAy4xOMuOCCw3JezAA0UOL3mw2+F9syZ68Sm5yUXRZHuajSzAdpeD3X7tOO4cC6YCvUVkBXRLWozWmI64/6WL/FhNdux/GMlRqWGbxQPg43pZfGs6VQD/p1BGpZTFk9zuQix0UMLPxfvjwkLYt97KK6KmbCv1YE8IedhkdBeVDh9OETPFa5/N9lGxocpraVivYYzmyHDg=
  bucket: obeo-m2doc-releases
  local-dir: "${TRAVIS_BUILD_DIR}/${TAG_OR_BRANCH}"
  acl: public_read
  skip_cleanup: true
  region: eu-west-1
  upload-dir: ${TAG_OR_BRANCH}
  on:
    all_branches: true
    repo: ObeoNetwork/M2Doc
    condition: $UPDATE_SITES = true

