# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Environment
      env:
        PROFILE: platform-2020-03,tests,updatesites
      run: |
        echo GITHUB_WORKSPACE $GITHUB_WORKSPACE
        echo GITHUB_REF $GITHUB_REF
        echo GITHUB_SHA $GITHUB_SHA
        echo GITHUB_EVENT_NAME $GITHUB_EVENT_NAME
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Setup website (documentation)
      run: if [[ "$PROFILE" == *"updatesites"* ]]; then chmod a+x ./scripts/website-install.sh && ./scripts/website-install.sh; fi

    - name: Setup MS Word add-in
      run: if [[ "$PROFILE" == *"updatesites"* ]]; then chmod a+x ./scripts/word-add-in-install.sh && ./scripts/word-add-in-install.sh; fi
    
    - name: Build website (documentation)
      run: |
        mkdir plugins/org.obeonetwork.m2doc.doc/doc
        export TAG=""
        if [[ "$(echo $GITHUB_REF | cut -d"/" -f2)" != "heads" ]]; then export TAG="$(echo $GITHUB_REF | cut -d"/" -f3)"; fi
        echo TAG $TAG
        if [[ "$PROFILE" == *"updatesites"* ]]; then chmod a+x ./scripts/website-build.sh && ./scripts/website-build.sh $TAG; fi

    - name: Build MS Word add-in
      run: |
        mkdir plugins/org.obeonetwork.m2doc.word.addin/dist/
        if [[ "$PROFILE" == *"updatesites"* ]]; then chmod a+x ./scripts/word-add-in-build.sh && ./scripts/word-add-in-build.sh; fi

    - name: Build with Maven
      env:
        MAVEN_OPTS: -XX:MaxPermSize=512m -Xmx2048m -Xms1024m
      uses: GabrielBB/xvfb-action@v1
      with:
        run: |
          echo PROFILE $PROFILE
          mvn clean verify -fae -P$PROFILE
